obj/adduserdlg.o: adduserdlg.cpp ../config.h adduserdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h \
 licq-locale.h /usr/include/libintl.h moc/moc_adduserdlg.h \
 moc/../adduserdlg.h
obj/authuserdlg.o: authuserdlg.cpp ../config.h authuserdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h \
 licq-locale.h /usr/include/libintl.h moc/moc_authuserdlg.h \
 moc/../authuserdlg.h
obj/awaymsgdlg.o: awaymsgdlg.cpp ../config.h awaymsgdlg.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h mledit.h licq-locale.h \
 /usr/include/libintl.h moc/moc_awaymsgdlg.h moc/../awaymsgdlg.h
obj/chatacceptdlg.o: chatacceptdlg.cpp ../config.h chatacceptdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h mledit.h \
 chatdlg.h licq-locale.h /usr/include/libintl.h \
 moc/moc_chatacceptdlg.h moc/../chatacceptdlg.h
obj/chatdlg.o: chatdlg.cpp ../config.h chatdlg.h mledit.h \
 ../../../src/inc/socket.h ../../../src/inc/buffer.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/support.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/icqpacket.h ../../../src/inc/user.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/log.h \
 ../../../src/inc/translate.h licq-locale.h /usr/include/libintl.h \
 moc/moc_chatdlg.h moc/../chatdlg.h
obj/editgrp.o: editgrp.cpp ../config.h editgrp.h ewidgets.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h licq-locale.h /usr/include/libintl.h \
 moc/moc_editgrp.h moc/../editgrp.h
obj/ewidgets.o: ewidgets.cpp ../config.h ewidgets.h outputwin.h \
 licq-locale.h /usr/include/libintl.h ../../../src/inc/log.h \
 ../../../src/inc/constants.h mledit.h moc/moc_ewidgets.h \
 moc/../ewidgets.h
obj/fileacceptdlg.o: fileacceptdlg.cpp ../config.h fileacceptdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h mledit.h \
 filedlg.h ewidgets.h licq-locale.h /usr/include/libintl.h \
 moc/moc_fileacceptdlg.h moc/../fileacceptdlg.h
obj/filedlg.o: filedlg.cpp ../config.h filedlg.h ../../../src/inc/user.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/constants.h \
 ../../../src/inc/icq-defines.h ../../../src/inc/file.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/buffer.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/support.h \
 ../../../src/inc/socket.h ewidgets.h ../../../src/inc/icqpacket.h \
 ../../../src/inc/log.h ../../../src/inc/translate.h licq-locale.h \
 /usr/include/libintl.h moc/moc_filedlg.h moc/../filedlg.h
obj/icqfunctions.o: icqfunctions.cpp ../config.h icqfunctions.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h mledit.h messagebox.h \
 ../../../src/inc/icqevent.h ../../../src/inc/socket.h \
 ../../../src/inc/icq.h ../../../src/inc/remoteserver.h \
 ../../../src/inc/onevent.h ewidgets.h sigman.h chatacceptdlg.h \
 chatdlg.h fileacceptdlg.h filedlg.h showawaymsgdlg.h \
 ../../../src/inc/countrycodes.h ../../../src/inc/log.h licq-locale.h \
 /usr/include/libintl.h moc/moc_icqfunctions.h moc/../icqfunctions.h
obj/licqgui.o: licqgui.cpp ../config.h licqgui.h mainwin.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h sigman.h \
 outputwin.h licq-locale.h /usr/include/libintl.h \
 ../../../src/inc/log.h mledit.h ../../../src/inc/plugin.h
obj/mainwin.o: mainwin.cpp ../config.h mainwin.h \
 ../../../src/inc/icq-defines.h gui-defines.h ../../../src/inc/log.h \
 ../../../src/inc/constants.h ../../../src/inc/translate.h \
 ../../../src/inc/utility.h ../../../src/inc/user.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/file.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/buffer.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/support.h adduserdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/socket.h \
 ../../../src/inc/icqevent.h ../../../src/inc/remoteserver.h \
 ../../../src/inc/onevent.h authuserdlg.h editgrp.h ewidgets.h \
 searchuserdlg.h sigman.h icqfunctions.h mledit.h messagebox.h \
 utilitydlg.h registeruser.h skinbrowser.h licq-locale.h \
 /usr/include/libintl.h userbox.h awaymsgdlg.h outputwin.h \
 optionsdlg.h skin.h wharf.h licq_qt-gui.conf.h moc/moc_mainwin.h \
 moc/../mainwin.h
obj/messagebox.o: messagebox.cpp ../config.h messagebox.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h licq-locale.h /usr/include/libintl.h
obj/mledit.o: mledit.cpp ../config.h mledit.h moc/moc_mledit.h \
 moc/../mledit.h
obj/optionsdlg.o: optionsdlg.cpp ../config.h optionsdlg.h ewidgets.h \
 ../../../src/inc/translate.h ../../../src/inc/log.h \
 ../../../src/inc/constants.h ../../../src/inc/support.h mainwin.h \
 licq-locale.h /usr/include/libintl.h ../../../src/inc/icq.h \
 ../../../src/inc/icq-defines.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/file.h ../../../src/inc/user.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/icqevent.h ../../../src/inc/remoteserver.h \
 ../../../src/inc/onevent.h userbox.h wharf.h moc/moc_optionsdlg.h \
 moc/../optionsdlg.h
obj/outputwin.o: outputwin.cpp ../config.h outputwin.h licq-locale.h \
 /usr/include/libintl.h ../../../src/inc/log.h \
 ../../../src/inc/constants.h mledit.h ../../../src/inc/icq-defines.h \
 moc/moc_outputwin.h moc/../outputwin.h
obj/registeruser.o: registeruser.cpp ../config.h registeruser.h \
 licq-locale.h /usr/include/libintl.h ewidgets.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h \
 moc/moc_registeruser.h moc/../registeruser.h
obj/searchuserdlg.o: searchuserdlg.cpp ../config.h searchuserdlg.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/constants.h ../../../src/inc/socket.h \
 ../../../src/inc/buffer.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/support.h ../../../src/inc/file.h \
 ../../../src/inc/user.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/icqevent.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h sigman.h \
 licq-locale.h /usr/include/libintl.h moc/moc_searchuserdlg.h \
 moc/../searchuserdlg.h
obj/showawaymsgdlg.o: showawaymsgdlg.cpp ../config.h showawaymsgdlg.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h mledit.h licq-locale.h \
 /usr/include/libintl.h moc/moc_showawaymsgdlg.h \
 moc/../showawaymsgdlg.h
obj/sigman.o: sigman.cpp sigman.h ../../../src/inc/log.h ../config.h \
 ../../../src/inc/constants.h ../../../src/inc/icqevent.h \
 ../../../src/inc/socket.h ../../../src/inc/buffer.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/support.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/icq.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/user.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/remoteserver.h ../../../src/inc/onevent.h \
 moc/moc_sigman.h moc/../sigman.h
obj/skin.o: skin.cpp ../config.h skin.h ../../../src/inc/file.h \
 ../../../src/inc/constants.h
obj/skinbrowser.o: skinbrowser.cpp ../config.h skinbrowser.h ewidgets.h \
 mainwin.h licq-locale.h /usr/include/libintl.h \
 ../../../src/inc/support.h ../../../src/inc/constants.h \
 ../../../src/inc/log.h moc/moc_skinbrowser.h moc/../skinbrowser.h
obj/userbox.o: userbox.cpp ../config.h userbox.h ../../../src/inc/user.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/constants.h \
 ../../../src/inc/icq-defines.h ../../../src/inc/file.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/buffer.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/support.h \
 gui-defines.h licq-locale.h /usr/include/libintl.h moc/moc_userbox.h \
 moc/../userbox.h
obj/utilitydlg.o: utilitydlg.cpp utilitydlg.h ewidgets.h ../config.h \
 ../../../src/inc/utility.h ../../../src/inc/user.h \
 ../../../src/inc/pthread_rdwr.h ../../../src/inc/constants.h \
 ../../../src/inc/icq-defines.h ../../../src/inc/file.h \
 ../../../src/inc/message.h ../../../src/inc/time-fix.h \
 ../../../src/inc/buffer.h ../../../src/inc/history.h \
 ../../../src/inc/userfcndlg.h ../../../src/inc/support.h \
 ../../../src/inc/icq.h ../../../src/inc/socket.h \
 ../../../src/inc/icqevent.h ../../../src/inc/remoteserver.h \
 ../../../src/inc/onevent.h moc/moc_utilitydlg.h moc/../utilitydlg.h
obj/wharf.o: wharf.cpp xpm/iconOnline.xpm xpm/iconOffline.xpm \
 xpm/iconAway.xpm xpm/iconFFC.xpm xpm/iconNA.xpm xpm/iconDND.xpm \
 xpm/iconInvisible.xpm xpm/iconOccupied.xpm xpm/iconBack.xpm \
 xpm/iconDigits.h xpm/iconMask.xpm wharf.h ../config.h mainwin.h \
 ../../../src/inc/user.h ../../../src/inc/pthread_rdwr.h \
 ../../../src/inc/constants.h ../../../src/inc/icq-defines.h \
 ../../../src/inc/file.h ../../../src/inc/message.h \
 ../../../src/inc/time-fix.h ../../../src/inc/buffer.h \
 ../../../src/inc/history.h ../../../src/inc/userfcndlg.h \
 ../../../src/inc/support.h moc/moc_wharf.h moc/../wharf.h
