static const char LICQ_CONF[] =
"\n"
"[licq]\n"
"Version = 710\n"
"\n"
"[plugins]\n"
"NumPlugins = 1\n"
"Plugin1 = qt-gui\n"
"\n"
"[network]\n"
"AllowNewUsers = 1\n"
"NumOfServers = 3\n"
"DefaultServerPort = 4000\n"
"Server1 = icq.mirabilis.com\n"
"Server2 = icq2.mirabilis.com\n"
"Server3 = icq3.mirabilis.com\n"
"TCPServerPort = 0\n"
"TCPServerPortRange = 0\n"
"TCPEnabled = true\n"
"FirewallHost = \n"
"MaxUsersPerPacket = 100\n"
"Errors = log.errors\n"
"Rejects = log.rejects\n"
"Translation = none\n"
"UrlViewer = viewurl-netscape.sh\n"
"Terminal = xterm -T Licq -e \n"
"IgnoreTypes = 0\n"
"\n"
"[onevent]\n"
"Enable = 1\n"
"Command = play\n"
"Message = ~/wavs/message.wav\n"
"Chat = ~/wavs/chat.wav\n"
"File = ~/wavs/file.wav\n"
"Url = ~/wavs/url.wav\n"
"OnlineNotify = ~/wavs/notify.wav\n"
"SysMsg = ~/wavs/sysmsg.wav\n"
"\n"
"[groups]\n"
"NumOfGroups = 3\n"
"DefaultGroup = 0\n"
"NewUserGroup = 1\n"
"Group1.name = New Users\n"
"Group2.name = Friends\n"
"Group3.name = Family\n"
"\n";

