static const char LICQ_CONF[] =
"\n"
"[licq]\n"
"Version = 850\n"
"\n"
"[plugins]\n"
"NumPlugins = 1\n"
"Plugin1 = qt-gui\n"
"\n"
"[network]\n"
"AllowNewUsers = 1\n"
"NumOfICQServers = 1\n"
"DefaultICQServerPort = 5190\n"
"ICQServer1 = login.icq.com\n"
"TCPServerPort = 0\n"
"TCPServerPortRange = 0\n"
"TCPEnabled = 1\n"
"MaxUsersPerPacket = 100\n"
"Errors = log.errors\n"
"Rejects = log.rejects\n"
"Translation = none\n"
"UrlViewer = viewurl-netscape.sh\n"
"Terminal = xterm -T Licq -e \n"
"IgnoreTypes = 0\n"
"\n"
"[onevent]\n"
"Enable = 1\n"
"Command = play\n"
"Message = /usr/share/licq/sounds/icq/Message.wav\n"
"Chat = /usr/share/licq/sounds/icq/Chat.wav\n"
"File = /usr/share/licq/sounds/icq/File.wav\n"
"Url = /usr/share/licq/sounds/icq/URL.wav\n"
"OnlineNotify = /usr/share/licq/sounds/icq/Notify.wav\n"
"SysMsg = /usr/share/licq/sounds/icq/System.wav\n"
"\n"
"[groups]\n"
"NumOfGroups = 3\n"
"DefaultGroup = 0\n"
"NewUserGroup = 1\n"
"Group1.name = New Users\n"
"Group2.name = Friends\n"
"Group3.name = Family\n"
"\n";

