/* Automatically generated by po2tbl.sed from Licq-Qt-GUI.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"KLicq (%1)", 2},
  {"Licq (%1)", 3},
  {"\
You have not yet registered a uin.  Select the\n\
\"Register\" option from the system menu to\n\
register an existing uin or create a new one.", 4},
  {"&System", 5},
  {"SysMsg", 6},
  {"%1 msg%2", 7},
  {" ", 8},
  {"s", 9},
  {"No msgs", 10},
  {"All Users", 11},
  {"Online Notify", 12},
  {"Visible List", 13},
  {"Invisible List", 14},
  {"Ignore List", 15},
  {"\
Successfully registered, your user identification\n\
number (UIN) is %ld.  Now log on and update your\n\
personal info.", 16},
  {"Registration failed.  See network window for details.", 17},
  {"Authorization granted.", 18},
  {"\
Are you sure you want to remove\n\
%1 (%2)\n\
from your contact list?", 19},
  {"Ok", 20},
  {"Cancel", 21},
  {"\
Are you sure you want to remove\n\
%1 (%2)\n\
from the '%3' group?", 22},
  {"\
Licq version %1.\n\
Qt GUI plugin version %2.\n\
\n\
Author: Graham Roff\n\
http://www.licq.org\n\
\n\
%3 (%4)\n\
%5 contacts.", 23},
  {"&Online", 24},
  {"&Away", 25},
  {"&Not Available", 26},
  {"O&ccupied", 27},
  {"&Do Not Disturb", 28},
  {"Free for C&hat", 29},
  {"O&ffline", 30},
  {"&Invisible", 31},
  {"&Send Message", 32},
  {"Send &Url", 33},
  {"Send &Chat Request", 34},
  {"Send &File Transfer", 35},
  {"&Add User", 36},
  {"S&earch for User", 37},
  {"A&uthorize User", 38},
  {"Edit Groups", 39},
  {"&Save All Users", 40},
  {"Register User", 41},
  {"Status Info", 42},
  {"Unknown Packets", 43},
  {"Errors", 44},
  {"Warnings", 45},
  {"Packets", 46},
  {"Set All", 47},
  {"Clear All", 48},
  {"User Functions", 49},
  {"&Status", 50},
  {"&Group", 51},
  {"Set &Auto Response", 52},
  {"Show &Network Window", 53},
  {"Use &Mini Mode", 54},
  {"Show Offline &Users", 55},
  {"&Options", 56},
  {"S&kin Browser", 57},
  {"Debug Level", 58},
  {"Next &Server", 59},
  {"Sa&ve Options", 60},
  {"&About", 61},
  {"E&xit", 62},
  {"From Current Group", 63},
  {"From Contact List", 64},
  {"&View Event", 65},
  {"Send Authorization", 66},
  {"Check &Auto Response", 67},
  {"User &Info", 68},
  {"User &Detail", 69},
  {"View &History", 70},
  {"Remove", 71},
  {"Add To Group", 72},
  {"&Utilities", 73},
  {"\
You are currently registered as\n\
UIN: %ld\n\
Base Directory: %s\n\
Rerun licq with the -b option to select a new\n\
base directory and then register a new user.", 74},
  {"Refusal Reason (if applicable):", 75},
  {"Accept", 76},
  {"Refuse", 77},
  {"Ignore", 78},
  {"Accept chat with ", 79},
  {"&Ok", 80},
  {"&Cancel", 81},
  {"Set Auto Response for %1:", 82},
  {"\
I am currently %1.\n\
You can leave me a message.", 83},
  {"Licq", 84},
  {"Authorize which user (UIN):", 85},
  {"New User UIN:", 86},
  {"&Alert User", 87},
  {"Remote - Not connected", 88},
  {"Local - ", 89},
  {"Close Chat", 90},
  {"Remote - Waiting for joiners...", 91},
  {"Remote - Received connection, shaking hands...", 92},
  {"Remote - ", 93},
  {"Remote - Connected, shaking hands...", 94},
  {"Remote - Connected, waiting for response...", 95},
  {"Accept file transfer from ", 96},
  {"ICQ file transfer", 97},
  {"Current file:", 98},
  {"Local file name:", 99},
  {"Unset", 100},
  {"N/A", 101},
  {"Current File", 102},
  {"Size:", 103},
  {"Trans:", 104},
  {"Time:", 105},
  {"BPS:", 106},
  {"ETA:", 107},
  {"Batch", 108},
  {"&Cancel Transfer", 109},
  {"Unknown", 110},
  {"%ld bytes", 111},
  {"File already exists and is at least as big as the incoming file.", 112},
  {"Overwrite", 113},
  {"File already exists and appears incomplete.", 114},
  {"Resume", 115},
  {"Open error - unable to open file for writing.", 116},
  {"Retry", 117},
  {"File transfer cancelled.", 118},
  {"Done", 119},
  {"%0.2f kb", 120},
  {"%ld b", 121},
  {"%.2f k", 122},
  {"Waiting for connection...", 123},
  {"Remote end disconnected.", 124},
  {"ICQ file transfer %1 %2", 125},
  {"from", 126},
  {"to", 127},
  {"Received init, waiting for batch info...", 128},
  {"Receiving file...", 129},
  {"File '%1' from %2 received successfully.", 130},
  {"File received.", 131},
  {"Connecting to remote...", 132},
  {"Connected, shaking hands...", 133},
  {"Connected, waiting for response...", 134},
  {"Sent batch info, waiting for ack...", 135},
  {"Starting transfer...", 136},
  {"Sending file...", 137},
  {"File sent.", 138},
  {"Sending of file '%1' to %2 completed successfully.", 139},
  {"File transfer complete.", 140},
  {"View Event", 141},
  {"Send Event", 142},
  {"Select Function", 143},
  {"Message", 144},
  {"URL", 145},
  {"Check Auto Response", 146},
  {"Chat Request", 147},
  {"File Transfer", 148},
  {"Send through server", 149},
  {"Urgent", 150},
  {"Spoof UIN:", 151},
  {"User Info", 152},
  {"Alias:", 153},
  {"Status:", 154},
  {"UIN:", 155},
  {"Name:", 156},
  {"EMail:", 157},
  {"History:", 158},
  {"IP:", 159},
  {"Authorization Needed", 160},
  {"Details", 161},
  {"Age:", 162},
  {"State:", 163},
  {"City:", 164},
  {"Country:", 165},
  {"Unspecified", 166},
  {"Unknown (unspecified)", 167},
  {"Homepage:", 168},
  {"Sex:", 169},
  {"Female", 170},
  {"Male", 171},
  {"Phone:", 172},
  {"About", 173},
  {"History", 174},
  {"History read only", 175},
  {"Auto Close", 176},
  {"Close", 177},
  {"Save", 178},
  {"Unknown (%1)", 179},
  {"Send", 180},
  {"Update", 181},
  {"Reply", 182},
  {"View URL?", 183},
  {"Yes", 184},
  {"No", 185},
  {"Authorize?", 186},
  {"Add?", 187},
  {"\
Spoofing messages is immoral and possibly illegal.\n\
In clicking OK you absolve the author from any \n\
responsibility for your actions.\n\
Do you want to continue?", 188},
  {"Message:", 189},
  {"URL:", 190},
  {"Description:", 191},
  {"Reason:", 192},
  {"Filename:", 193},
  {"\
Message is %1 characters, over the ICQ98 limit of %2.  \n\
Licq, ICQ99, and other clones support longer messages \n\
however ICQ98 will not. Continue?", 194},
  {"Sending msg ", 195},
  {"through server", 196},
  {"direct", 197},
  {"Fetching...", 198},
  {"Sending URL ", 199},
  {"Sending chat request ", 200},
  {"Sending file transfer ", 201},
  {"Update local or server information?", 202},
  {"Local", 203},
  {"Server", 204},
  {"Updating server...", 205},
  {"Updating...", 206},
  {"done", 207},
  {"failed", 208},
  {"timed out", 209},
  {"error", 210},
  {"\
%s is in %s mode:\n\
%s\n\
[Send \"urgent\" to ignore]", 211},
  {"%s refused %s, send through server.", 212},
  {"\
%s%s with %s refused:\n\
%s%s", 213},
  {"N", 214},
  {"Event Type", 215},
  {"Time Received", 216},
  {"Flags", 217},
  {"Licq Options", 218},
  {"Apply", 219},
  {"What's This?", 220},
  {"Font", 221},
  {"The font used for all widgets", 222},
  {"Font:", 223},
  {"Select Font", 224},
  {"Select a font from the system list", 225},
  {"Use Font Styles", 226},
  {"\
Use italics and bold in the user list to indicate special characteristics \
such as online notify and visible list", 227},
  {"Show Grid Lines", 228},
  {"Draw boxes around each square in the user list", 229},
  {"Show Column Headers", 230},
  {"\
Turns on or off the display of headers above each column in the user list", 231},
  {"Show User Dividers", 232},
  {"Show the \"--online--\" and \"--offline--\" bars in the contact list", 233},
  {"Auto Close Function Window", 234},
  {"\
Sets the default behavior for auto closing the user function window after a \
succesful event", 235},
  {"Title", 236},
  {"The string which will appear in the list box column header", 237},
  {"Format", 238},
  {"\
The format string used to define what willappear in each column, see OnEvent \
Command formore information about valid % values", 239},
  {"Width", 240},
  {"The width of the column", 241},
  {"Alignment", 242},
  {"The alignment of the column", 243},
  {"Column %1", 244},
  {"Left", 245},
  {"Right", 246},
  {"Center", 247},
  {"OnEvents Enabled", 248},
  {"Enable running of \"Command\" when the relevant event occurs.", 249},
  {"Command:", 250},
  {"\
Command to execute when an event is received.  It will be passed the \
relevant parameters from below.  Parameters can contain the following \
expressions which will be replaced with the relevant information:\n\
%a - user alias\n\
%i - user ip\n\
%p - user port\n\
%e - email\n\
%n - full name\n\
%f - first name\n\
%l - last name\n\
%u - uin\n\
%w - webpage\n\
%h - phone number", 251},
  {"Parameters", 252},
  {"Parameter for received messages", 253},
  {"Parameter for received URLs", 254},
  {"Chat Request:", 255},
  {"Parameter for received chat requests", 256},
  {"File Transfer:", 257},
  {"Parameter for received file transfers", 258},
  {"Online Notify:", 259},
  {"Parameter for online notification", 260},
  {"System Msg:", 261},
  {"Parameter for received system messages", 262},
  {"Servers:", 263},
  {"List of servers to connect to (read-only for now)", 264},
  {"Default Server Port:", 265},
  {"Default port to connect to on the server (should be 4000)", 266},
  {"TCP Server Port:", 267},
  {"\
TCP port for local server.  Set to \"0\" for system assigned port.  Use if \
you are behinda firewall or using ip masquerading.", 268},
  {"Max Users per Packet:", 269},
  {"\
Leave at 125 unless all your users appear offline when they should not be.  \
Then lower it until they appear again (try ~100).", 270},
  {"Auto Logon:", 271},
  {"Automatically log on when first starting up.", 272},
  {"Offline", 273},
  {"Online", 274},
  {"Away", 275},
  {"Not Available", 276},
  {"Occupied", 277},
  {"Do Not Disturb", 278},
  {"Free for Chat", 279},
  {"Invisible", 280},
  {"Auto Away:", 281},
  {"\
Number of minutes of inactivity after which to automatically be marked \
\"away\".  Set to \"0\" to disable.", 282},
  {"Auto N/A:", 283},
  {"\
Number of minutes of inactivity after which to automatically be marked \"not \
available\".  Set to \"0\" to disable.", 284},
  {"Web Presence Enabled", 285},
  {"\
Web presence allows users to see if you are online through your web \
indicator.", 286},
  {"Hide IP", 287},
  {"Hiding ip stops users from seeing your ip.", 288},
  {"Allow New Users", 289},
  {"\
Determines if new users are automatically addedto your list or must first \
request authorization.", 290},
  {"Error Log:", 291},
  {"Url Viewer:", 292},
  {"\
The command to run to view a URL.  Will be passed the URL as a parameter.", 293},
  {"Terminal:", 294},
  {"The command to run to start your terminal program.", 295},
  {"Translation:", 296},
  {"Sets which translation table should be used for translating characters.", 297},
  {"ERROR", 298},
  {"none", 299},
  {"Use Dock Icon", 300},
  {"Controls whether or not the dockable icon should be displayed.", 301},
  {"64 x 48 Dock Icon", 302},
  {"\
Selects between the standard 64x64 icon used in the WindowMaker/Afterstep \
wharf and a shorter 64x48 icon for use in the Gnome/KDE panel.", 303},
  {"Appearance", 304},
  {"Columns", 305},
  {"OnEvent", 306},
  {"Network", 307},
  {"Extensions", 308},
  {"Licq Network Log", 309},
  {"C&lear", 310},
  {"&Close", 311},
  {"Alias", 312},
  {"UIN", 313},
  {"Name", 314},
  {"Email", 315},
  {"First Name:", 316},
  {"Last Name:", 317},
  {"&Name", 318},
  {"Email Address:", 319},
  {"&Email", 320},
  {"UIN#:", 321},
  {"&Uin#", 322},
  {"&Search", 323},
  {"Search Again", 324},
  {"Enter search parameters and select 'Search'", 325},
  {"A&lert User", 326},
  {"&Done", 327},
  {"Searching (this can take awhile)...", 328},
  {"More users found. Narrow search.", 329},
  {"Search failed.", 330},
  {"\
Sorry, but this user is already\n\
on your contact list as\n\
'%1'\n\
\n\
You can't add a user twice.", 331},
  {"&OK", 332},
  {"&Show Again", 333},
  {"%1 Response for %2", 334},
  {"S", 335},
  {"Uin:", 336},
  {"Password:", 337},
  {"Verify:", 338},
  {"&Register Existing User", 339},
  {"Licq User Registration", 340},
  {"\
If you are registering a new uin, choose a password and click \"OK\".\n\
If you already have a uin, then toggle \"Register Existing User\",\n\
enter your uin and your password, and click \"OK\"", 341},
  {"Invalid password, must be 8 characters or less.", 342},
  {"Passwords do not match, try again.", 343},
  {"Invalid UIN.  Try again.", 344},
  {"Registered succesfully.  Now log on and update your personal info.", 345},
  {"User Registration in Progress...", 346},
  {"Skins", 347},
  {"Icons", 348},
  {"Licq Skin Browser", 349},
};

int _msg_tbl_length = 349;
