/* Automatically generated by po2tbl.sed from Licq-Qt-GUI.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"KLicq (%s)", 2},
  {"Licq (%s)", 3},
  {"\
You have not yet registered a uin.  Select the\n\
\"Register\" option from the system menu to\n\
register an existing uin or create a new one.", 4},
  {"&System", 5},
  {"SysMsg", 6},
  {"%d msg%c", 7},
  {"No msgs", 8},
  {"\
Successfully registered, your user identification\n\
number (UIN) is %ld.  Now log on and update your\n\
personal info.", 9},
  {"Registration failed.  See network window for details.", 10},
  {"Authorization granted.", 11},
  {"\
Are you sure you want to remove\n\
%s (%ld)\n\
from your contact list?", 12},
  {"Ok", 13},
  {"Cancel", 14},
  {"\
Are you sure you want to remove\n\
%s (%ld)\n\
from the '%s' group?", 15},
  {"\
Licq version %s.\n\
Qt GUI plugin version %s.\n\
\n\
Author: Graham Roff\n\
http://www.licq.org\n\
\n\
%s (%ld)\n\
%d contacts.", 16},
  {"&Online", 17},
  {"&Away", 18},
  {"&Not Available", 19},
  {"O&ccupied", 20},
  {"&Do Not Disturb", 21},
  {"Free for C&hat", 22},
  {"O&ffline", 23},
  {"&Invisible", 24},
  {"&Send Message", 25},
  {"Send &Url", 26},
  {"Send &Chat Request", 27},
  {"Send &File Transfer", 28},
  {"&Add User", 29},
  {"S&earch for User", 30},
  {"A&uthorize User", 31},
  {"Edit Groups", 32},
  {"&Update Contact List", 33},
  {"Update All Users", 34},
  {"&Redraw User Window", 35},
  {"&Save All Users", 36},
  {"Register User", 37},
  {"Status Info", 38},
  {"Unknown Packets", 39},
  {"Errors", 40},
  {"Warnings", 41},
  {"Packets", 42},
  {"Set All", 43},
  {"Clear All", 44},
  {"User Functions", 45},
  {"&Status", 46},
  {"&Group", 47},
  {"Set &Auto Response", 48},
  {"Show &Network Window", 49},
  {"Use &Mini Mode", 50},
  {"Show Offline &Users", 51},
  {"&Options", 52},
  {"S&kin Browser", 53},
  {"Debug Level", 54},
  {"Next &Server", 55},
  {"Sa&ve Options", 56},
  {"&About", 57},
  {"E&xit", 58},
  {"From Current Group", 59},
  {"From Contact List", 60},
  {"&View Event", 61},
  {"Send Authorization", 62},
  {"Check &Auto Response", 63},
  {"User &Info", 64},
  {"User &Detail", 65},
  {"View &History", 66},
  {"Online Notify", 67},
  {"Invisible List", 68},
  {"Visible List", 69},
  {"Remove", 70},
  {"Add To Group", 71},
  {"&Utilities", 72},
  {"\
You are currently registered as\n\
UIN: %ld\n\
Base Directory: %s\n\
Rerun licq with the -b option to select a new\n\
base directory and then register a new user.", 73},
  {"Refusal Reason (if applicable):", 74},
  {"Accept", 75},
  {"Refuse", 76},
  {"Ignore", 77},
  {"Accept chat with %s?", 78},
  {"&Ok", 79},
  {"&Cancel", 80},
  {"Set Auto Response for %s:", 81},
  {"\
I am currently %s.\n\
You can leave me a message.", 82},
  {"Licq", 83},
  {"Authorize which user (UIN):", 84},
  {"New User UIN:", 85},
  {"&Alert User", 86},
  {"Remote - Not connected", 87},
  {"Local - %s", 88},
  {"Close Chat", 89},
  {"Remote - Waiting for joiners...", 90},
  {"Remote - Received connection, shaking hands...", 91},
  {"Remote - %s", 92},
  {"Remote - Connected, shaking hands...", 93},
  {"Remote - Connected, waiting for response...", 94},
  {"Accept file transfer from %s?", 95},
  {"ICQ file transfer", 96},
  {"Current file:", 97},
  {"Local file name:", 98},
  {"Unset", 99},
  {"N/A", 100},
  {"Current File", 101},
  {"Size:", 102},
  {"Trans:", 103},
  {"Time:", 104},
  {"BPS:", 105},
  {"ETA:", 106},
  {"&Cancel Transfer", 107},
  {"Unknown", 108},
  {"%ld bytes", 109},
  {"File already exists and is at least as big as the incoming file.", 110},
  {"Overwrite", 111},
  {"File already exists and appears incomplete.", 112},
  {"Resume", 113},
  {"Open error - unable to open file for writing.", 114},
  {"Retry", 115},
  {"File transfer cancelled.", 116},
  {"Done", 117},
  {"%0.2f kb", 118},
  {"%ld b", 119},
  {"%.2f k", 120},
  {"Waiting for connection...", 121},
  {"Remote end disconnected.", 122},
  {"ICQ file transfer %s %s", 123},
  {"from", 124},
  {"to", 125},
  {"Received init, waiting for batch info...", 126},
  {"Receiving file...", 127},
  {"\
%sFile transfer of\n\
'%s'\n\
from %s completed successfully.\n", 128},
  {"File received.", 129},
  {"Connecting to remote...", 130},
  {"Connected, shaking hands...", 131},
  {"Connected, waiting for response...", 132},
  {"Sent batch info, waiting for ack...", 133},
  {"Starting transfer...", 134},
  {"Sending file...", 135},
  {"File sent.", 136},
  {"\
%sFile transfer of\n\
'%s'\n\
to %s completed successfully.\n", 137},
  {"File transfer complete.", 138},
  {"View Event", 139},
  {"Send Event", 140},
  {"Select Function", 141},
  {"Message", 142},
  {"URL", 143},
  {"Check Auto Response", 144},
  {"Chat Request", 145},
  {"File Transfer", 146},
  {"Send through server", 147},
  {"Urgent", 148},
  {"Spoof UIN:", 149},
  {"User Info", 150},
  {"Alias:", 151},
  {"Status:", 152},
  {"UIN:", 153},
  {"Name:", 154},
  {"EMail:", 155},
  {"History:", 156},
  {"IP:", 157},
  {"Authorization Needed", 158},
  {"Details", 159},
  {"Age:", 160},
  {"State:", 161},
  {"City:", 162},
  {"Country:", 163},
  {"Unspecified", 164},
  {"Unknown (unspecified)", 165},
  {"Homepage:", 166},
  {"Sex:", 167},
  {"Female", 168},
  {"Male", 169},
  {"Phone:", 170},
  {"About", 171},
  {"History", 172},
  {"History read only", 173},
  {"Auto Close", 174},
  {"Close", 175},
  {"Save", 176},
  {"Unknown (%d)", 177},
  {"Send", 178},
  {"Update", 179},
  {"Reply", 180},
  {"View URL?", 181},
  {"Yes", 182},
  {"No", 183},
  {"Authorize?", 184},
  {"Add?", 185},
  {"\
Spoofing messages is immoral and possibly illegal.\n\
In clicking OK you absolve the author from any \n\
responsibility for your actions.\n\
Do you want to continue?", 186},
  {"Message:", 187},
  {"URL:", 188},
  {"Description:", 189},
  {"Reason:", 190},
  {"Filename:", 191},
  {"\
Message is %d characters, over the ICQ98 limit of %d.  \n\
Licq, ICQ99, and other clones support longer messages \n\
however ICQ98 will not.  Continue?", 192},
  {"Sending msg ", 193},
  {"server", 194},
  {"direct", 195},
  {"Fetching...", 196},
  {"Sending URL ", 197},
  {"Sending chat request ", 198},
  {"Sending file transfer ", 199},
  {"Update local or server information?", 200},
  {"Local", 201},
  {"Server", 202},
  {"Updating server...", 203},
  {"Updating...", 204},
  {"done", 205},
  {"failed", 206},
  {"timed out", 207},
  {"error", 208},
  {"\
%s is in %s mode.\n\
Send \"urgent\" to ignore.", 209},
  {"%s refused %s, send through server.", 210},
  {"\
%s%s with %s refused:\n\
%s%s", 211},
  {"N", 212},
  {"Event Type", 213},
  {"Time Received", 214},
  {"Flags", 215},
  {"Licq Options", 216},
  {"Apply", 217},
  {"What's This?", 218},
  {"Font", 219},
  {"The font used for all widgets", 220},
  {"Font:", 221},
  {"Select Font", 222},
  {"Select a font from the system list", 223},
  {"Use Font Styles", 224},
  {"\
Use italics and bold in the user list to indicate special characteristics \
such as online notify and visible list", 225},
  {"Show Grid Lines", 226},
  {"Draw boxes around each square in the user list", 227},
  {"Show Column Headers", 228},
  {"\
Turns on or off the display of headers above each column in the user list", 229},
  {"Show User Dividers", 230},
  {"Show the \"--online--\" and \"--offline--\" bars in the contact list", 231},
  {"Auto Close Function Window", 232},
  {"\
Sets the default behavior for auto closing the user function window after a \
succesful event", 233},
  {"Info", 234},
  {"Width", 235},
  {"Alignment", 236},
  {"Column %d", 237},
  {"Alias", 238},
  {"UIN", 239},
  {"Name", 240},
  {"EMail", 241},
  {"Left", 242},
  {"Right", 243},
  {"Center", 244},
  {"OnEvents Enabled", 245},
  {"Enable running of \"Command\" when the relevant event occurs.", 246},
  {"Command:", 247},
  {"\
Command to execute when an event is received.  It will be passed the \
relevant parameters from below.  Parameters can contain the following \
expressions which will be replaced with the relevant information:\n\
%a - user alias\n\
%i - user ip\n\
%p - user port\n\
%e - email\n\
%n - full name\n\
%f - first name\n\
%l - last name\n\
%u - uin\n\
%w - webpage\n\
%h - phone number", 248},
  {"Parameters", 249},
  {"Parameter for received messages", 250},
  {"Parameter for received URLs", 251},
  {"Chat Request:", 252},
  {"Parameter for received chat requests", 253},
  {"File Transfer:", 254},
  {"Parameter for received file transfers", 255},
  {"Online Notify:", 256},
  {"Parameter for online notification", 257},
  {"Servers:", 258},
  {"List of servers to connect to (read-only for now)", 259},
  {"Default Server Port:", 260},
  {"Default port to connect to on the server (should be 4000)", 261},
  {"TCP Server Port:", 262},
  {"\
TCP port for local server.  Set to \"0\" for system assigned port.  Use if \
you are behinda firewall or using ip masquerading.", 263},
  {"Max Users per Packet:", 264},
  {"\
Leave at 125 unless all your users appear offline when they should not be.  \
Then lower it until they appear again (try ~100).", 265},
  {"Auto Logon:", 266},
  {"Automatically log on when first starting up.", 267},
  {"Offline", 268},
  {"Online", 269},
  {"Away", 270},
  {"Not Available", 271},
  {"Occupied", 272},
  {"Do Not Disturb", 273},
  {"Free for Chat", 274},
  {"Invisible", 275},
  {"Auto Away:", 276},
  {"\
Number of minutes of inactivity after which to automatically be marked \
\"away\".  Set to \"0\" to disable.", 277},
  {"Auto N/A:", 278},
  {"\
Number of minutes of inactivity after which to automatically be marked \"not \
available\".  Set to \"0\" to disable.", 279},
  {"Web Presence Enabled", 280},
  {"\
Web presence allows users to see if you are online through your web \
indicator.", 281},
  {"Hide IP", 282},
  {"Hiding ip stops users from seeing your ip.", 283},
  {"Error Log:", 284},
  {"Url Viewer:", 285},
  {"\
The command to run to view a URL.  Will be passed the URL as a parameter.", 286},
  {"Terminal:", 287},
  {"The command to run to start your terminal program.", 288},
  {"Translation:", 289},
  {"Sets which translation table should be used for translating characters.", 290},
  {"ERROR", 291},
  {"none", 292},
  {"Use Dock Icon", 293},
  {"Controls whether or not the dockable icon should be displayed.", 294},
  {"64 x 48 Dock Icon", 295},
  {"\
Selects between the standard 64x64 icon used in the WindowMaker/Afterstep \
wharf and a shorter 64x48 icon for use in the Gnome/KDE panel.", 296},
  {"Appearance", 297},
  {"Columns", 298},
  {"OnEvent", 299},
  {"Network", 300},
  {"Extensions", 301},
  {"Hide Window", 302},
  {"Clear", 303},
  {"Email", 304},
  {"First Name:", 305},
  {"Last Name:", 306},
  {"&Name", 307},
  {"Email Address:", 308},
  {"&Email", 309},
  {"UIN#:", 310},
  {"&Uin#", 311},
  {"&Search", 312},
  {"Search Again", 313},
  {"Searching (this can take awhile)...", 314},
  {"A&lert User", 315},
  {"&Done", 316},
  {"More users found. Narrow search.", 317},
  {"Search failed.", 318},
  {"&Show Again", 319},
  {"%s Message for %s", 320},
  {"S", 321},
  {"EMail Address", 322},
  {"Uin:", 323},
  {"Password:", 324},
  {"Verify:", 325},
  {"&Register Existing User", 326},
  {"Licq User Registration", 327},
  {"\
If you are registering a new uin, choose a password and click \"OK\".\n\
If you already have a uin, then toggle \"Register Existing User\",\n\
enter your uin and your password, and click \"OK\"", 328},
  {"Invalid password, must be 8 characters or less.", 329},
  {"Passwords do not match, try again.", 330},
  {"Invalid UIN.  Try again.", 331},
  {"Registered succesfully.  Now log on and update your personal info.", 332},
  {"User Registration in Progress...", 333},
  {"Skins", 334},
  {"Icons", 335},
  {"Licq Skin Browser", 336},
};

int _msg_tbl_length = 336;
