<!DOCTYPE TS><TS>
<context>
    <name></name>
</context>
<context>
    <name>AddUserDlg</name>
</context>
<context>
    <name>AuthUserDlg</name>
</context>
<context>
    <name>AwayMsgDlg</name>
</context>
<context>
    <name>CEditFileListDlg</name>
</context>
<context>
    <name>CFileDlg</name>
</context>
<context>
    <name>CForwardDlg</name>
</context>
<context>
    <name>CJoinChatDlg</name>
</context>
<context>
    <name>CMMSendDlg</name>
</context>
<context>
    <name>CMMUserView</name>
</context>
<context>
    <name>CMainWindow</name>
</context>
<context>
    <name>CQtLogWindow</name>
</context>
<context>
    <name>CRandomChatDlg</name>
</context>
<context>
    <name>CRefuseDlg</name>
</context>
<context>
    <name>CSetRandomChatGroupDlg</name>
</context>
<context>
    <name>CUtilityDlg</name>
</context>
<context>
    <name>ChatDlg</name>
</context>
<context>
    <name>CustomAwayMsgDlg</name>
</context>
<context>
    <name>EditFileDlg</name>
</context>
<context>
    <name>Event</name>
</context>
<context>
    <name>HintsDlg</name>
</context>
<context>
    <name>OptionsDlg</name>
</context>
<context>
    <name>RegisterUserDlg</name>
</context>
<context>
    <name>SearchUserDlg</name>
</context>
<context>
    <name>SecurityDlg</name>
</context>
<context>
    <name>UserSendCommon</name>
</context>
</TS>
