obj/buffer.o: buffer.cpp ../../config.h ../inc/buffer.h ../inc/log.h \
 ../inc/constants.h
obj/file.o: file.cpp ../../config.h ../inc/file.h ../inc/log.h \
 ../inc/constants.h
obj/history.o: history.cpp ../../config.h ../inc/history.h ../inc/log.h \
 ../inc/constants.h
obj/icqd.o: icqd.cpp ../../config.h ../inc/time-fix.h ../inc/log.h \
 ../inc/constants.h ../inc/translate.h plugind.h ../inc/icqevent.h \
 ../inc/socket.h ../inc/buffer.h ../inc/pthread_rdwr.h \
 ../inc/support.h ../inc/message.h ../inc/icqpacket.h ../inc/user.h \
 ../inc/icq-defines.h ../inc/file.h ../inc/history.h \
 ../inc/userfcndlg.h ../licq.h ../inc/icqd.h ../inc/remoteserver.h \
 ../inc/onevent.h icq-udp.h icq-tcp.h icq-threads.h
obj/icqevent.o: icqevent.cpp ../../config.h ../inc/icqevent.h \
 ../inc/socket.h ../inc/buffer.h ../inc/pthread_rdwr.h \
 ../inc/support.h ../inc/constants.h ../inc/message.h \
 ../inc/time-fix.h ../inc/icqpacket.h ../inc/user.h \
 ../inc/icq-defines.h ../inc/file.h ../inc/history.h \
 ../inc/userfcndlg.h ../inc/log.h
obj/icqpacket.o: icqpacket.cpp ../../config.h ../inc/icqpacket.h \
 ../inc/user.h ../inc/pthread_rdwr.h ../inc/constants.h \
 ../inc/icq-defines.h ../inc/file.h ../inc/message.h ../inc/time-fix.h \
 ../inc/buffer.h ../inc/history.h ../inc/userfcndlg.h ../inc/support.h \
 ../inc/socket.h ../inc/translate.h ../inc/log.h
obj/log.o: log.cpp ../../config.h ../inc/log.h ../inc/constants.h
obj/message.o: message.cpp ../../config.h ../inc/message.h \
 ../inc/time-fix.h ../inc/buffer.h ../inc/constants.h ../inc/user.h \
 ../inc/pthread_rdwr.h ../inc/icq-defines.h ../inc/file.h \
 ../inc/history.h ../inc/userfcndlg.h ../inc/support.h
obj/onevent.o: onevent.cpp ../inc/onevent.h ../inc/support.h \
 ../../config.h ../inc/user.h ../inc/pthread_rdwr.h ../inc/constants.h \
 ../inc/icq-defines.h ../inc/file.h ../inc/message.h ../inc/time-fix.h \
 ../inc/buffer.h ../inc/history.h ../inc/userfcndlg.h
obj/plugind.o: plugind.cpp plugind.h ../inc/icqevent.h ../../config.h \
 ../inc/socket.h ../inc/buffer.h ../inc/pthread_rdwr.h \
 ../inc/support.h ../inc/constants.h ../inc/message.h \
 ../inc/time-fix.h
obj/remoteserver.o: remoteserver.cpp ../../config.h ../inc/remoteserver.h \
 ../inc/constants.h
obj/sar.o: sar.cpp ../../config.h ../inc/sar.h ../inc/file.h \
 ../inc/pthread_rdwr.h ../inc/log.h ../inc/constants.h sar.conf.h
obj/socket.o: socket.cpp ../../config.h ../inc/socket.h ../inc/buffer.h \
 ../inc/pthread_rdwr.h ../inc/support.h ../inc/constants.h \
 ../inc/icq-defines.h ../inc/log.h ../inc/user.h ../inc/file.h \
 ../inc/message.h ../inc/time-fix.h ../inc/history.h \
 ../inc/userfcndlg.h
obj/translate.o: translate.cpp ../../config.h ../inc/translate.h \
 ../inc/log.h ../inc/constants.h
obj/user.o: user.cpp ../../config.h ../inc/support.h ../inc/user.h \
 ../inc/pthread_rdwr.h ../inc/constants.h ../inc/icq-defines.h \
 ../inc/file.h ../inc/message.h ../inc/time-fix.h ../inc/buffer.h \
 ../inc/history.h ../inc/userfcndlg.h ../inc/countrycodes.h \
 ../inc/log.h ../inc/icqpacket.h ../inc/socket.h
obj/utility.o: utility.cpp ../../config.h ../inc/utility.h ../inc/user.h \
 ../inc/pthread_rdwr.h ../inc/constants.h ../inc/icq-defines.h \
 ../inc/file.h ../inc/message.h ../inc/time-fix.h ../inc/buffer.h \
 ../inc/history.h ../inc/userfcndlg.h ../inc/support.h ../inc/log.h
