#!/bin/sh

set -eu

if [ $# -ne 4 ]; then
  echo "Usage: $0 <major> <minor> <release> <extra>" >&2
  exit 1
fi

find . \( -name version.cmake -o -name LicqVersion.cmake \) -print0 |
  xargs -0 sed -i -r \
      -e "s/^(set\((LICQ|PLUGIN)_VERSION_MAJOR) [^)]+/\1 $1/" \
      -e "s/^(set\((LICQ|PLUGIN)_VERSION_MINOR) [^)]+/\1 $2/" \
      -e "s/^(set\((LICQ|PLUGIN)_VERSION_RELEASE) [^)]+/\1 $3/" \
      -e "s/^(set\((LICQ|PLUGIN)_VERSION_EXTRA) [^)]+/\1 \"$4\"/"
