#!/bin/sh
#
# Copy to .git/hooks and make executable.
#
# Copyright (c) 2011, 2013 Erik Johansson <erijo@licq.org>
# Copyright (c) 2011 Anders Olofsson <flynd@licq.org>
# Distributed under the terms of the GNU GPL version 2.
#

year=$(date +%Y)
exit_status=0

error()
{
  echo "Error: $*" >& 2
  exit_status=1
}

verify_copyright_year()
{
  file="$1"
  sha1="$2"
  if ! git cat-file -p $sha1 | grep -q "Copyright"; then
    if echo "$file" | grep -Eq '\.(c|cpp|h)$'; then
      error "no copyright line in '$file'"
    fi
    return
  fi

  if ! git cat-file -p $sha1 | grep -Eq "Copyright.*$year"; then
    if echo "$file" | grep -Eq '\.pot$'; then
      return
    fi
    error "copyright line in '$file' does not include current year"
  fi
}


# Loop on lines, not words
IFS="
"

for file in $(git diff-index --cached --full-index --diff-filter=AM HEAD); do
  sha1_staged=$(echo $file | cut -d' ' -f4)
  filename=$(echo $file | cut -d'	' -f2)

  if echo "$filename" | grep -q "3rdparty/"; then
    continue
  fi

  verify_copyright_year "$filename" "$sha1_staged"
done
unset IFS

exit $exit_status
